# Generated by Django 3.1.2 on 2021-01-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tel',
            field=models.IntegerField(verbose_name='Номер телефона'),
        ),
    ]
