# Generated by Django 3.1.5 on 2021-01-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0004_auto_20210114_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(null=True, upload_to='', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='imgproduct',
            name='url',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Ссылка на картинку'),
        ),
    ]
