# Generated by Django 3.1.5 on 2021-01-14 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0006_auto_20210114_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainPage.customer', verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='imgproduct',
            name='url',
            field=models.ImageField(null=True, upload_to='', verbose_name='Ссылка на картинку'),
        ),
    ]
