# Generated by Django 3.1.5 on 2021-01-14 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0007_auto_20210114_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableorders',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainPage.order', verbose_name='Заказ'),
            preserve_default=False,
        ),
    ]
