# Generated by Django 3.1.5 on 2021-01-14 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0008_tableorders_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableorders',
            name='order',
        ),
    ]
