# Generated by Django 3.1.5 on 2021-01-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0009_remove_tableorders_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='fathName',
            field=models.CharField(blank=True, max_length=30, verbose_name='Отчество клиента'),
        ),
    ]
